<?php
/**
 * SkinOperationsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.server
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace com.github.asyncmc.mojang.api.php.server;

use \com.github.asyncmc.mojang.api.php.server\Configuration;
use \com.github.asyncmc.mojang.api.php.server\ApiException;
use \com.github.asyncmc.mojang.api.php.server\ObjectSerializer;

/**
 * SkinOperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.server
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SkinOperationsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changePlayerSkin
     *
     * Changes the player skin by URL.
     *
     */
    public function testChangePlayerSkin()
    {
    }

    /**
     * Test case for resetPlayerSkin
     *
     * Resets the player skin to default.
     *
     */
    public function testResetPlayerSkin()
    {
    }

    /**
     * Test case for uploadPlayerSkin
     *
     * Changes the player skin by upload.
     *
     */
    public function testUploadPlayerSkin()
    {
    }
}
