# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MojangAPI.Model.CurrentPlayerIDs do
  @moduledoc """
  The current player, demo and legacy status of a player identified by the id
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"legacy",
    :"demo"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"name" => String.t,
    :"legacy" => boolean() | nil,
    :"demo" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: MojangAPI.Model.CurrentPlayerIDs do
  def decode(value, _options) do
    value
  end
end

