<?php
/**
 * MiscellaneousApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.symfony.server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\OrderStatisticsRequest;
use com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\OrderStatisticsResponse;

/**
 * MiscellaneousApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface MiscellaneousApiInterface
{

    /**
     * Sets authentication method MojangStatisticsToken
     *
     * @param string $value Value of the MojangStatisticsToken authentication method.
     *
     * @return void
     */
    public function setMojangStatisticsToken($value);

    /**
     * Operation getOrdersStatistics
     *
     * Get statistics on the sales of Minecraft.
     *
     * @param  com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\OrderStatisticsRequest $orderStatisticsRequest  The payload is a json list of options under the metricKeys key. You will receive a single object corresponding to the sum of sales of the requested type(s). You must request at least one type of sale. Below is the default list used by https://minecraft.net/en/stats/ (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\OrderStatisticsResponse[]
     *
     */
    public function getOrdersStatistics(OrderStatisticsRequest $orderStatisticsRequest, &$responseCode, array &$responseHeaders);
}
