<?php
/**
 * SkinOperationsApiInterface
 * PHP version 5
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.symfony.server
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.api;

use Symfony\Component\HttpFoundation\File\UploadedFile;
use com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\Error;
use com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\SkinModel;

/**
 * SkinOperationsApiInterface Interface Doc Comment
 *
 * @category Interface
 * @package  com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.api
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */
interface SkinOperationsApiInterface
{

    /**
     * Sets authentication method PlayerAccessToken
     *
     * @param string $value Value of the PlayerAccessToken authentication method.
     *
     * @return void
     */
    public function setPlayerAccessToken($value);

    /**
     * Operation changePlayerSkin
     *
     * Changes the player skin by URL
     *
     * @param  string $strippedUuid  The player UUID without hyphens (required)
     * @param  string $url  The URL which Mojang servers will download and apply the skin (required)
     * @param  com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\SkinModel $model   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function changePlayerSkin($strippedUuid, $url, SkinModel $model = null, &$responseCode, array &$responseHeaders);

    /**
     * Operation resetPlayerSkin
     *
     * Resets the player skin to default
     *
     * @param  string $strippedUuid  The player UUID without hyphens (required)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function resetPlayerSkin($strippedUuid, &$responseCode, array &$responseHeaders);

    /**
     * Operation uploadPlayerSkin
     *
     * Changes the player skin by upload
     *
     * @param  string $strippedUuid  The player UUID without hyphens (required)
     * @param  UploadedFile $file  The skin image in PNG format (required)
     * @param  com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model\SkinModel $model   (optional)
     * @param  integer $responseCode     The HTTP response code to return
     * @param  array   $responseHeaders  Additional HTTP headers to return with the response ()
     *
     * @return void
     *
     */
    public function uploadPlayerSkin($strippedUuid, UploadedFile $file, SkinModel $model = null, &$responseCode, array &$responseHeaders);
}
