<?php
/**
 * OrderStatisticsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.symfony.server\Tests\Model
 * @author   openapi-generator contributors
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace com.github.asyncmc.mojang.api.php.symfony.server\com.github.asyncmc.mojang.api.php.symfony.model;

/**
 * OrderStatisticsResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description A json object is returned with the total amount of copies sold, the amount of copies sold in the last 24h and how many sales there are per second.
/**
 * @package     com.github.asyncmc.mojang.api.php.symfony.server\Tests\Model
 * @author      openapi-generator contributors
 * @link        https://github.com/openapitools/openapi-generator
 */
class OrderStatisticsResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrderStatisticsResponse"
     */
    public function testOrderStatisticsResponse()
    {
        $testOrderStatisticsResponse = new OrderStatisticsResponse();
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "last24h"
     */
    public function testPropertyLast24h()
    {
    }

    /**
     * Test attribute "saleVelocityPerSeconds"
     */
    public function testPropertySaleVelocityPerSeconds()
    {
    }
}
