/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAISkinOperationsApiHandler_H
#define OAI_OAISkinOperationsApiHandler_H

#include <QObject>

#include "OAIError.h"
#include "OAISkinModel.h"
#include <QIODevice>
#include <QString>

namespace OpenAPI {

class OAISkinOperationsApiHandler : public QObject
{
    Q_OBJECT
    
public:
    OAISkinOperationsApiHandler();
    virtual ~OAISkinOperationsApiHandler();


public slots:
    virtual void changePlayerSkin(QString stripped_uuid, QString url, OAISkinModel model);
    virtual void resetPlayerSkin(QString stripped_uuid);
    virtual void uploadPlayerSkin(QString stripped_uuid, QIODevice* file, OAISkinModel model);
    

};

}

#endif // OAI_OAISkinOperationsApiHandler_H
