# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule com.github.asyncmc.mojang.status.elixir.server.Model.ApiStatus do
  @moduledoc """
  The status of a Mojang services. Possible values are green (no issues), yellow (some issues), red (service unavailable).
  """

  @derive [Poison.Encoder]
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }
end

defimpl Poison.Decoder, for: com.github.asyncmc.mojang.status.elixir.server.Model.ApiStatus do
  def decode(value, _options) do
    value
  end
end

