/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SecurityAnswerId } from './securityAnswerId';


/**
 * A security question answer given by the player using the id given by Mojang
 */
export interface SecurityAnswer extends SecurityAnswerId { 
}
