/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIAuthenticationRequest.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIAuthenticationRequest::OAIAuthenticationRequest(QString json) {
    init();
    this->fromJson(json);
}

OAIAuthenticationRequest::OAIAuthenticationRequest() {
    init();
}

OAIAuthenticationRequest::~OAIAuthenticationRequest() {
    this->cleanup();
}

void
OAIAuthenticationRequest::init() {
    username = new QString("");
    m_username_isSet = false;
    password = new QString("");
    m_password_isSet = false;
}

void
OAIAuthenticationRequest::cleanup() {
    if(username != nullptr) { 
        delete username;
    }
    if(password != nullptr) { 
        delete password;
    }
}

OAIAuthenticationRequest*
OAIAuthenticationRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIAuthenticationRequest::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&username, pJson["username"], "QString", "QString");
    
    ::OpenAPI::setValue(&password, pJson["password"], "QString", "QString");
    
}

QString
OAIAuthenticationRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIAuthenticationRequest::asJsonObject() {
    QJsonObject obj;
    if(username != nullptr && *username != QString("")){
        toJsonValue(QString("username"), username, obj, QString("QString"));
    }
    if(password != nullptr && *password != QString("")){
        toJsonValue(QString("password"), password, obj, QString("QString"));
    }

    return obj;
}

QString*
OAIAuthenticationRequest::getUsername() {
    return username;
}
void
OAIAuthenticationRequest::setUsername(QString* username) {
    this->username = username;
    this->m_username_isSet = true;
}

QString*
OAIAuthenticationRequest::getPassword() {
    return password;
}
void
OAIAuthenticationRequest::setPassword(QString* password) {
    this->password = password;
    this->m_password_isSet = true;
}


bool
OAIAuthenticationRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(username != nullptr && *username != QString("")){ isObjectUpdated = true; break;}
        if(password != nullptr && *password != QString("")){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

