/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIReducedUserData.h
 *
 * 
 */

#ifndef OAIReducedUserData_H_
#define OAIReducedUserData_H_

#include <QJsonObject>


#include "OAIGameProfileProperty.h"
#include "OAIHttpRequest.h"
#include <QList>

#include "OAIObject.h"

namespace OpenAPI {

class OAIReducedUserData: public OAIObject {
public:
    OAIReducedUserData();
    OAIReducedUserData(QString json);
    ~OAIReducedUserData();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIReducedUserData* fromJson(QString jsonString) override;

    OAIHttpRequestInputFileElement* getId();
    void setId(OAIHttpRequestInputFileElement* id);

    QList<OAIGameProfileProperty*>* getProperties();
    void setProperties(QList<OAIGameProfileProperty*>* properties);


    virtual bool isSet() override;

private:
    OAIHttpRequestInputFileElement* id;
    bool m_id_isSet;

    QList<OAIGameProfileProperty*>* properties;
    bool m_properties_isSet;

};

}

#endif /* OAIReducedUserData_H_ */
