/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * Contact: team@openapitools.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */

package org.openapitools.server.model

case class NameChange(
  /* The new player name */
  name: String,

  /* Time which the name was changed in UNIX Timestamp without milliseconds. Usually absent for the first entry. */
  changedToAt: Option[Long]

 )
