//
// PrivateUserData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct PrivateUserData: Codable {

    public var _id: URL?
    public var properties: [GameProfileProperty]?

    public init(_id: URL?, properties: [GameProfileProperty]?) {
        self._id = _id
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case properties
    }


}

