/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * The current player, demo and legacy status of a player identified by the id
 */
export interface CurrentPlayerIDs {
    /**
     * The player UUID without hyphens
     */
    "id": string;
    /**
     * The current name being used by this player
     */
    "name": string;
    /**
     * If account has not been converted
     */
    "legacy"?: boolean;
    /**
     * If the player has not puchased the game
     */
    "demo"?: boolean;
}

