<?php
/**
 * OrderStatisticsRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the OrderStatisticsRequest model.
 *
 * The body of the request to get the order statistics
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class OrderStatisticsRequest 
{
        /**
     * @var OpenAPI\Server\Model\OrderStatistic[]
     * @SerializedName("metricKeys")
     * @Assert\NotNull()
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\OrderStatistic")
     * })
     * @Type("array<OpenAPI\Server\Model\OrderStatistic>")
     */
    protected $metricKeys;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->metricKeys = isset($data['metricKeys']) ? $data['metricKeys'] : null;
    }

    /**
     * Gets metricKeys.
     *
     * @return OpenAPI\Server\Model\OrderStatistic[]
     */
    public function getMetricKeys()
    {
        return $this->metricKeys;
    }

    /**
     * Sets metricKeys.
     *
     * @param OpenAPI\Server\Model\OrderStatistic[] $metricKeys
     *
     * @return $this
     */
    public function setMetricKeys(array $metricKeys)
    {
        $this->metricKeys = $metricKeys;

        return $this;
    }
}


