/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIOrderStatisticsResponse.h
 *
 * A json object is returned with the total amount of copies sold, the amount of copies sold in the last 24h and how many sales there are per second.
 */

#ifndef OAIOrderStatisticsResponse_H_
#define OAIOrderStatisticsResponse_H_

#include <QJsonObject>



#include "OAIObject.h"

namespace OpenAPI {

class OAIOrderStatisticsResponse: public OAIObject {
public:
    OAIOrderStatisticsResponse();
    OAIOrderStatisticsResponse(QString json);
    ~OAIOrderStatisticsResponse();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIOrderStatisticsResponse* fromJson(QString jsonString) override;

    qint64 getTotal();
    void setTotal(qint64 total);

    qint64 getLast24h();
    void setLast24h(qint64 last24h);

    double getSaleVelocityPerSeconds();
    void setSaleVelocityPerSeconds(double sale_velocity_per_seconds);


    virtual bool isSet() override;

private:
    qint64 total;
    bool m_total_isSet;

    qint64 last24h;
    bool m_last24h_isSet;

    double sale_velocity_per_seconds;
    bool m_sale_velocity_per_seconds_isSet;

};

}

#endif /* OAIOrderStatisticsResponse_H_ */
