/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIUploadSkinRequest.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIUploadSkinRequest::OAIUploadSkinRequest(QString json) {
    init();
    this->fromJson(json);
}

OAIUploadSkinRequest::OAIUploadSkinRequest() {
    init();
}

OAIUploadSkinRequest::~OAIUploadSkinRequest() {
    this->cleanup();
}

void
OAIUploadSkinRequest::init() {
    model = new OAISkinModel();
    m_model_isSet = false;
    file = new QString("");
    m_file_isSet = false;
}

void
OAIUploadSkinRequest::cleanup() {
    if(model != nullptr) { 
        delete model;
    }
    if(file != nullptr) { 
        delete file;
    }
}

OAIUploadSkinRequest*
OAIUploadSkinRequest::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIUploadSkinRequest::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&model, pJson["model"], "OAISkinModel", "OAISkinModel");
    
    ::OpenAPI::setValue(&file, pJson["file"], "OAIHttpRequestInputFileElement", "OAIHttpRequestInputFileElement");
    
}

QString
OAIUploadSkinRequest::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIUploadSkinRequest::asJsonObject() {
    QJsonObject obj;
    if((model != nullptr) && (model->isSet())){
        toJsonValue(QString("model"), model, obj, QString("OAISkinModel"));
    }
    if((file != nullptr) && (file->isSet())){
        toJsonValue(QString("file"), file, obj, QString("OAIHttpRequestInputFileElement"));
    }

    return obj;
}

OAISkinModel*
OAIUploadSkinRequest::getModel() {
    return model;
}
void
OAIUploadSkinRequest::setModel(OAISkinModel* model) {
    this->model = model;
    this->m_model_isSet = true;
}

OAIHttpRequestInputFileElement*
OAIUploadSkinRequest::getFile() {
    return file;
}
void
OAIUploadSkinRequest::setFile(OAIHttpRequestInputFileElement* file) {
    this->file = file;
    this->m_file_isSet = true;
}


bool
OAIUploadSkinRequest::isSet(){
    bool isObjectUpdated = false;
    do{
        if(model != nullptr && model->isSet()){ isObjectUpdated = true; break;}
        if(file != nullptr && file->isSet()){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

