# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MojangSessionAPI.Model.SessionApiError do
  @moduledoc """
  An object describing giving a bit of information about the error
  """

  @derive [Poison.Encoder]
  defstruct [
    :"error",
    :"path"
  ]

  @type t :: %__MODULE__{
    :"error" => String.t | nil,
    :"path" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MojangSessionAPI.Model.SessionApiError do
  def decode(value, _options) do
    value
  end
end

