#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Mojang API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 2020-06-05
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIOrderStatisticsResponse
@end

@interface OAIOrderStatisticsResponse : OAIObject

/* total amount sold 
 */
@property(nonatomic) NSNumber* total;
/* total sold in last 24 hours 
 */
@property(nonatomic) NSNumber* last24h;
/* decimal average sales per second 
 */
@property(nonatomic) NSNumber* saleVelocityPerSeconds;

@end
