dependencies:
  factories:
    Zend\Expressive\Router\RouterInterface: Articus\PathHandler\Router\Factory\FastRouteAnnotation

Articus\PathHandler\Middleware:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    abstract_factories:
      - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Articus\PathHandler\Router\FastRouteAnnotation:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\OrdersStatistics
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\ProfilesMinecraft
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserProfileStrippedUuidSkin
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserProfilesStrippedUuidNames
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserSecurityChallenges
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserSecurityLocation
    - com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UsersProfilesMinecraftUsername

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\OrdersStatistics: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\ProfilesMinecraft: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserProfileStrippedUuidSkin: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserProfilesStrippedUuidNames: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserSecurityChallenges: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UserSecurityLocation: []
  com.github.asyncmc.mojang.api.php.ze.ph.server\com.github.asyncmc.mojang.api.php.ze.ph.api\UsersProfilesMinecraftUsername: []
