dependencies:
  factories:
    Zend\Expressive\Router\RouterInterface: Articus\PathHandler\Router\Factory\FastRouteAnnotation

Articus\PathHandler\Middleware:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    abstract_factories:
      - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Articus\PathHandler\Router\FastRouteAnnotation:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    - App\Handler\OrdersStatistics
    - App\Handler\ProfilesMinecraft
    - App\Handler\UserProfileStrippedUuidSkin
    - App\Handler\UserProfilesStrippedUuidNames
    - App\Handler\UserSecurityChallenges
    - App\Handler\UserSecurityLocation
    - App\Handler\UsersProfilesMinecraftUsername

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\OrdersStatistics: []
  App\Handler\ProfilesMinecraft: []
  App\Handler\UserProfileStrippedUuidSkin: []
  App\Handler\UserProfilesStrippedUuidNames: []
  App\Handler\UserSecurityChallenges: []
  App\Handler\UserSecurityLocation: []
  App\Handler\UsersProfilesMinecraftUsername: []
