--  Mojang Session API
--  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
--  ------------ EDIT NOTE ------------
--  This file was generated with openapi-generator.  You can modify it to implement
--  the server.  After you modify this file, you should add the following line
--  to the .openapi-generator-ignore file:
--
--  src/com-github-asyncmc-mojang-sessions-ada-server-model.ads
--
--  Then, you can drop this edit note comment.
--  ------------ EDIT NOTE ------------
package com.github is

end com.github;
