/**
 * Mojang Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIPlayerSkinMetadata.h
 *
 * Contains details about the skin
 */

#ifndef OAIPlayerSkinMetadata_H_
#define OAIPlayerSkinMetadata_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIPlayerSkinMetadata: public OAIObject {
public:
    OAIPlayerSkinMetadata();
    OAIPlayerSkinMetadata(QString json);
    ~OAIPlayerSkinMetadata();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIPlayerSkinMetadata* fromJson(QString jsonString) override;

    QString* getModel();
    void setModel(QString* model);


    virtual bool isSet() override;

private:
    QString* model;
    bool m_model_isSet;

};

}

#endif /* OAIPlayerSkinMetadata_H_ */
