/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GameProfile {
    'agent'?: string;
    'id'?: string;
    'name'?: string;
    'userId'?: string;
    /**
    * Unix timestamp in milliseconds
    */
    'createdAt'?: number;
    'legacyProfile'?: boolean;
    'suspended'?: boolean;
    'paid'?: boolean;
    'migrated'?: boolean;
    'legacy'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "agent",
            "baseName": "agent",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "number"
        },
        {
            "name": "legacyProfile",
            "baseName": "legacyProfile",
            "type": "boolean"
        },
        {
            "name": "suspended",
            "baseName": "suspended",
            "type": "boolean"
        },
        {
            "name": "paid",
            "baseName": "paid",
            "type": "boolean"
        },
        {
            "name": "migrated",
            "baseName": "migrated",
            "type": "boolean"
        },
        {
            "name": "legacy",
            "baseName": "legacy",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GameProfile.attributeTypeMap;
    }
}

