/*
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccessKeys;
import org.openapitools.client.model.Authentication;
import org.openapitools.client.model.AuthenticationRequest;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.RefreshRequest;
import org.openapitools.client.model.RefreshResponse;
import org.openapitools.client.model.UsernamePassword;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authenticateTest() throws ApiException {
        AuthenticationRequest authenticationRequest = null;
        Authentication response = api.authenticate(authenticationRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void invalidateTest() throws ApiException {
        AccessKeys accessKeys = null;
        api.invalidate(accessKeys);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void refreshTest() throws ApiException {
        RefreshRequest refreshRequest = null;
        RefreshResponse response = api.refresh(refreshRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void siginoutTest() throws ApiException {
        UsernamePassword usernamePassword = null;
        api.siginout(usernamePassword);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void validateTest() throws ApiException {
        AccessKeys accessKeys = null;
        api.validate(accessKeys);

        // TODO: test validations
    }
    
}
