/* 
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct MiscellaneousApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> MiscellaneousApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> MiscellaneousApiClient<C> {
        MiscellaneousApiClient {
            configuration: configuration,
        }
    }
}

pub trait MiscellaneousApi {
    fn get_orders_statistics(&self, order_statistics_request: ::models::OrderStatisticsRequest) -> Box<Future<Item = ::models::OrderStatisticsResponse, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>MiscellaneousApi for MiscellaneousApiClient<C> {
    fn get_orders_statistics(&self, order_statistics_request: ::models::OrderStatisticsRequest) -> Box<Future<Item = ::models::OrderStatisticsResponse, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Post, "/orders/statistics".to_string())
            .with_auth(__internal_request::Auth::Basic)
            .with_body_param(order_statistics_request)
            .execute(self.configuration.borrow())
    }

}
