//
// PlayerTexture.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Provide links to the player&#39;s skin and cape */
open class PlayerTexture: JSONEncodable {

    public var SKIN: PlayerSkinURL?
    public var CAPE: PlayerTextureURL?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["SKIN"] = self.SKIN?.encodeToJSON()
        nillableDictionary["CAPE"] = self.CAPE?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

