=begin
Mojang Session API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2020-06-05
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class BansController < ApplicationController

  def get_blocked_server_hashes
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
