{-
   Mojang Authentication API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 2020-06-05

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.GameProfile exposing (GameProfile, decoder, encoder)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias GameProfile =
    { agent : Maybe (String)
    , id : Maybe (String)
    , name : Maybe (String)
    , userId : Maybe (String)
    , createdAt : Maybe (Int)
    , legacyProfile : Maybe (Bool)
    , suspended : Maybe (Bool)
    , paid : Maybe (Bool)
    , migrated : Maybe (Bool)
    , legacy : Maybe (Bool)
    }


decoder : Decoder GameProfile
decoder =
    Decode.succeed GameProfile
        |> optional "agent" (Decode.nullable Decode.string) Nothing
        |> optional "id" (Decode.nullable Decode.string) Nothing
        |> optional "name" (Decode.nullable Decode.string) Nothing
        |> optional "userId" (Decode.nullable Decode.string) Nothing
        |> optional "createdAt" (Decode.nullable Decode.int) Nothing
        |> optional "legacyProfile" (Decode.nullable Decode.bool) Nothing
        |> optional "suspended" (Decode.nullable Decode.bool) Nothing
        |> optional "paid" (Decode.nullable Decode.bool) Nothing
        |> optional "migrated" (Decode.nullable Decode.bool) Nothing
        |> optional "legacy" (Decode.nullable Decode.bool) Nothing



encoder : GameProfile -> Encode.Value
encoder model =
    Encode.object
        [ ( "agent", Maybe.withDefault Encode.null (Maybe.map Encode.string model.agent) )
        , ( "id", Maybe.withDefault Encode.null (Maybe.map Encode.string model.id) )
        , ( "name", Maybe.withDefault Encode.null (Maybe.map Encode.string model.name) )
        , ( "userId", Maybe.withDefault Encode.null (Maybe.map Encode.string model.userId) )
        , ( "createdAt", Maybe.withDefault Encode.null (Maybe.map Encode.int model.createdAt) )
        , ( "legacyProfile", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.legacyProfile) )
        , ( "suspended", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.suspended) )
        , ( "paid", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.paid) )
        , ( "migrated", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.migrated) )
        , ( "legacy", Maybe.withDefault Encode.null (Maybe.map Encode.bool model.legacy) )

        ]


