/*
 * Mojang Session API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2020-06-05
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// PlayerSkinMetadata - Contains details about the skin
type PlayerSkinMetadata struct {

	// The player model, currently only \"slim\" (Alex) is valid, for Steve's model this property must be absent.
	Model string `json:"model,omitempty"`
}
