# Mojang API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# OpenAPI spec version: 2020-06-05
# 
# Generated by: https://openapi-generator.tech


#' ApiStatus Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ApiStatus <- R6::R6Class(
  'ApiStatus',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      ApiStatusObject <- list()

      ApiStatusObject
    },
    fromJSON = function(ApiStatusJson) {
      ApiStatusObject <- jsonlite::fromJSON(ApiStatusJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(ApiStatusJson) {
      ApiStatusObject <- jsonlite::fromJSON(ApiStatusJson)
    }
  )
)
