/* 
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OrderStatisticsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderStatisticsRequestTests
    {
        // TODO uncomment below to declare an instance variable for OrderStatisticsRequest
        //private OrderStatisticsRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderStatisticsRequest
            //instance = new OrderStatisticsRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderStatisticsRequest
        /// </summary>
        [Test]
        public void OrderStatisticsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderStatisticsRequest
            //Assert.IsInstanceOfType<OrderStatisticsRequest> (instance, "variable 'instance' is a OrderStatisticsRequest");
        }


        /// <summary>
        /// Test the property 'MetricKeys'
        /// </summary>
        [Test]
        public void MetricKeysTest()
        {
            // TODO unit test for the property 'MetricKeys'
        }

    }

}
