=begin
Mojang API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2020-06-05
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class SecurityQuestionAnswerController < ApplicationController

  def check_security_status
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def list_pending_security_questions
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def send_security_question_answers
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
