# Mojang API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# OpenAPI spec version: 2020-06-05
# 
# Generated by: https://openapi-generator.tech


#' Error Class
#'
#' @field error 
#' @field errorMessage 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Error <- R6::R6Class(
  'Error',
  public = list(
    `error` = NULL,
    `errorMessage` = NULL,
    initialize = function(`error`, `errorMessage`){
      if (!missing(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
      if (!missing(`errorMessage`)) {
        stopifnot(is.character(`errorMessage`), length(`errorMessage`) == 1)
        self$`errorMessage` <- `errorMessage`
      }
    },
    toJSON = function() {
      ErrorObject <- list()
      if (!is.null(self$`error`)) {
        ErrorObject[['error']] <- self$`error`
      }
      if (!is.null(self$`errorMessage`)) {
        ErrorObject[['errorMessage']] <- self$`errorMessage`
      }

      ErrorObject
    },
    fromJSON = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      if (!is.null(ErrorObject$`error`)) {
        self$`error` <- ErrorObject$`error`
      }
      if (!is.null(ErrorObject$`errorMessage`)) {
        self$`errorMessage` <- ErrorObject$`errorMessage`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "error": %s,
           "errorMessage": %s
        }',
        self$`error`,
        self$`errorMessage`
      )
    },
    fromJSONString = function(ErrorJson) {
      ErrorObject <- jsonlite::fromJSON(ErrorJson)
      self$`error` <- ErrorObject$`error`
      self$`errorMessage` <- ErrorObject$`errorMessage`
    }
  )
)
