# Mojang API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# OpenAPI spec version: 2020-06-05
# 
# Generated by: https://openapi-generator.tech


#' SecurityAnswer Class
#'
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SecurityAnswer <- R6::R6Class(
  'SecurityAnswer',
  public = list(
    `id` = NULL,
    initialize = function(`id`){
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      SecurityAnswerObject <- list()
      if (!is.null(self$`id`)) {
        SecurityAnswerObject[['id']] <- self$`id`
      }

      SecurityAnswerObject
    },
    fromJSON = function(SecurityAnswerJson) {
      SecurityAnswerObject <- jsonlite::fromJSON(SecurityAnswerJson)
      if (!is.null(SecurityAnswerObject$`id`)) {
        self$`id` <- SecurityAnswerObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %d
        }',
        self$`id`
      )
    },
    fromJSONString = function(SecurityAnswerJson) {
      SecurityAnswerObject <- jsonlite::fromJSON(SecurityAnswerJson)
      self$`id` <- SecurityAnswerObject$`id`
    }
  )
)
