# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule MojangAuthenticationAPI.Model.RefreshResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accessToken",
    :"clientToken"
  ]

  @type t :: %__MODULE__{
    :"accessToken" => String.t,
    :"clientToken" => String.t | nil
  }
end

defimpl Poison.Decoder, for: MojangAuthenticationAPI.Model.RefreshResponse do
  def decode(value, _options) do
    value
  end
end

