/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MojangAuthenticationApi);
  }
}(this, function(expect, MojangAuthenticationApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MojangAuthenticationApi.GameProfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GameProfile', function() {
    it('should create an instance of GameProfile', function() {
      // uncomment below and update the code to test GameProfile
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be.a(MojangAuthenticationApi.GameProfile);
    });

    it('should have the property agent (base name: "agent")', function() {
      // uncomment below and update the code to test the property agent
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "userId")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property legacyProfile (base name: "legacyProfile")', function() {
      // uncomment below and update the code to test the property legacyProfile
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property suspended (base name: "suspended")', function() {
      // uncomment below and update the code to test the property suspended
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property paid (base name: "paid")', function() {
      // uncomment below and update the code to test the property paid
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property migrated (base name: "migrated")', function() {
      // uncomment below and update the code to test the property migrated
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

    it('should have the property legacy (base name: "legacy")', function() {
      // uncomment below and update the code to test the property legacy
      //var instance = new MojangAuthenticationApi.GameProfile();
      //expect(instance).to.be();
    });

  });

}));
