--[[
  Mojang API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 2020-06-05
  
  Generated by: https://openapi-generator.tech
]]

-- current_player_i_ds class
local current_player_i_ds = {}
local current_player_i_ds_mt = {
	__name = "current_player_i_ds";
	__index = current_player_i_ds;
}

local function cast_current_player_i_ds(t)
	return setmetatable(t, current_player_i_ds_mt)
end

local function new_current_player_i_ds(id, name, legacy, demo)
	return cast_current_player_i_ds({
		["id"] = id;
		["name"] = name;
		["legacy"] = legacy;
		["demo"] = demo;
	})
end

return {
	cast = cast_current_player_i_ds;
	new = new_current_player_i_ds;
}
