--[[
  Mojang API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 2020-06-05
  
  Generated by: https://openapi-generator.tech
]]

-- name_change class
local name_change = {}
local name_change_mt = {
	__name = "name_change";
	__index = name_change;
}

local function cast_name_change(t)
	return setmetatable(t, name_change_mt)
end

local function new_name_change(name, changed_to_at)
	return cast_name_change({
		["name"] = name;
		["changedToAt"] = changed_to_at;
	})
end

return {
	cast = cast_name_change;
	new = new_name_change;
}
