/*
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2020-06-05
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// A security question answer id given by Mojang
type SecurityAnswerId struct {
	// A number giver by Mojang to reply a question
	Id int32 `json:"id"`
}
