# coding: utf-8

"""
    Mojang API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 2020-06-05
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.order_statistics_request import OrderStatisticsRequest  # noqa: E501
from openapi_client.rest import ApiException


class TestOrderStatisticsRequest(unittest.TestCase):
    """OrderStatisticsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderStatisticsRequest(self):
        """Test OrderStatisticsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.order_statistics_request.OrderStatisticsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
