/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICurrentPlayerIDs.h
 *
 * The current player, demo and legacy status of a player identified by the id
 */

#ifndef OAICurrentPlayerIDs_H
#define OAICurrentPlayerIDs_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAICurrentPlayerIDs: public OAIObject {
public:
    OAICurrentPlayerIDs();
    OAICurrentPlayerIDs(QString json);
    ~OAICurrentPlayerIDs() override;
    void init();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getId() const;
    void setId(const QString &id);

    QString getName() const;
    void setName(const QString &name);

    bool isLegacy() const;
    void setLegacy(const bool &legacy);

    bool isDemo() const;
    void setDemo(const bool &demo);

    virtual bool isSet() const override;

private:
    QString id;
    bool m_id_isSet;

    QString name;
    bool m_name_isSet;

    bool legacy;
    bool m_legacy_isSet;

    bool demo;
    bool m_demo_isSet;

};

}

#endif // OAICurrentPlayerIDs_H
