/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINameChange.h
 *
 * A registered name change.
 */

#ifndef OAINameChange_H
#define OAINameChange_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAINameChange: public OAIObject {
public:
    OAINameChange();
    OAINameChange(QString json);
    ~OAINameChange() override;
    void init();

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    QString getName() const;
    void setName(const QString &name);

    qint64 getChangedToAt() const;
    void setChangedToAt(const qint64 &changed_to_at);

    virtual bool isSet() const override;

private:
    QString name;
    bool m_name_isSet;

    qint64 changed_to_at;
    bool m_changed_to_at_isSet;

};

}

#endif // OAINameChange_H
