/**
* Mojang API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 2020-06-05
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "Inline_object.h"

namespace org {
namespace openapitools {
namespace server {
namespace model {

Inline_object::Inline_object()
{
    m_ModelIsSet = false;
    
}

Inline_object::~Inline_object()
{
}

void Inline_object::validate()
{
    // TODO: implement validation
}

nlohmann::json Inline_object::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    if(m_ModelIsSet)
    {
        val["model"] = ModelBase::toJson(m_Model);
    }
    val["file"] = ModelBase::toJson(m_file);
    

    return val;
}

void Inline_object::fromJson(const nlohmann::json& val)
{
    if(val.find("model") != val.end())
    {
        if(!val["model"].is_null())
        {
            SkinModel newItem;
            newItem.fromJson(val["model"]);
            setModel( newItem );
        }
        
    }
    
}


SkinModel Inline_object::getModel() const
{
    return m_Model;
}
void Inline_object::setModel(SkinModel const& value)
{
    m_Model = value;
    m_ModelIsSet = true;
}
bool Inline_object::modelIsSet() const
{
    return m_ModelIsSet;
}
void Inline_object::unsetModel()
{
    m_ModelIsSet = false;
}
std::string Inline_object::getFile() const
{
    return m_file;
}
void Inline_object::setFile(std::string const& value)
{
    m_file = value;
    
}

}
}
}
}

