/**
* Mojang API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 2020-06-05
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "SkinModel.h"

namespace com {
namespace github {
namespace asyncmc {
namespace mojang {
namespace api {
namespace cpp {
namespace pistache {
namespace server {
namespace model {

SkinModel::SkinModel()
{
    
}

SkinModel::~SkinModel()
{
}

void SkinModel::validate()
{
    // TODO: implement validation
}

nlohmann::json SkinModel::toJson() const
{
    nlohmann::json val = nlohmann::json::object();

    

    return val;
}

void SkinModel::fromJson(const nlohmann::json& val)
{
    
}



}
}
}
}
}
}
}
}
}

