{-
   Mojang API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 2020-06-05

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.InlineObject1 exposing (InlineObject1, decoder, encoder)

import Data.SkinModel as SkinModel exposing (SkinModel)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


{-| Request Mojang to download a skin from an URL and apply to the player
-}
type alias InlineObject1 =
    { model : Maybe (SkinModel)
    , url : String
    }


decoder : Decoder InlineObject1
decoder =
    Decode.succeed InlineObject1
        |> optional "model" (Decode.nullable SkinModel.decoder) Nothing
        |> required "url" Decode.string



encoder : InlineObject1 -> Encode.Value
encoder model =
    Encode.object
        [ ( "model", Maybe.withDefault Encode.null (Maybe.map SkinModel.encoder model.model) )
        , ( "url", Encode.string model.url )

        ]


