{-
   Mojang API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 2020-06-05

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.NameChange exposing (NameChange, decoder, encoder)

import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


{-| A registered name change.
-}
type alias NameChange =
    { name : String
    , changedToAt : Maybe (Int)
    }


decoder : Decoder NameChange
decoder =
    Decode.succeed NameChange
        |> required "name" Decode.string
        |> optional "changedToAt" (Decode.nullable Decode.int) Nothing



encoder : NameChange -> Encode.Value
encoder model =
    Encode.object
        [ ( "name", Encode.string model.name )
        , ( "changedToAt", Maybe.withDefault Encode.null (Maybe.map Encode.int model.changedToAt) )

        ]


