{-
   Mojang Session API
   No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

   OpenAPI spec version: 2020-06-05

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PlayerTexture exposing (PlayerTexture, decoder, encoder)

import Data.PlayerSkinURL as PlayerSkinURL exposing (PlayerSkinURL)
import Data.PlayerTextureURL as PlayerTextureURL exposing (PlayerTextureURL)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


{-| Provide links to the player's skin and cape
-}
type alias PlayerTexture =
    { sKIN : Maybe (PlayerSkinURL)
    , cAPE : Maybe (PlayerTextureURL)
    }


decoder : Decoder PlayerTexture
decoder =
    Decode.succeed PlayerTexture
        |> optional "SKIN" (Decode.nullable PlayerSkinURL.decoder) Nothing
        |> optional "CAPE" (Decode.nullable PlayerTextureURL.decoder) Nothing



encoder : PlayerTexture -> Encode.Value
encoder model =
    Encode.object
        [ ( "SKIN", Maybe.withDefault Encode.null (Maybe.map PlayerSkinURL.encoder model.sKIN) )
        , ( "CAPE", Maybe.withDefault Encode.null (Maybe.map PlayerTextureURL.encoder model.cAPE) )

        ]


