--[[
  Mojang Authentication API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 2020-06-05
  
  Generated by: https://openapi-generator.tech
]]

-- authentication class
local authentication = {}
local authentication_mt = {
	__name = "authentication";
	__index = authentication;
}

local function cast_authentication(t)
	return setmetatable(t, authentication_mt)
end

local function new_authentication(access_token, client_token)
	return cast_authentication({
		["accessToken"] = access_token;
		["clientToken"] = client_token;
	})
end

return {
	cast = cast_authentication;
	new = new_authentication;
}
