--[[
  Mojang Authentication API
 
  No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 
  OpenAPI spec version: 2020-06-05
  
  Generated by: https://openapi-generator.tech
]]

-- reduced_user_data class
local reduced_user_data = {}
local reduced_user_data_mt = {
	__name = "reduced_user_data";
	__index = reduced_user_data;
}

local function cast_reduced_user_data(t)
	return setmetatable(t, reduced_user_data_mt)
end

local function new_reduced_user_data(id, properties)
	return cast_reduced_user_data({
		["id"] = id;
		["properties"] = properties;
	})
end

return {
	cast = cast_reduced_user_data;
	new = new_reduced_user_data;
}
