# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.com.github.asyncmc.mojang.sessions.python.flask.model.base_model_ import Model
from openapi_server import util


class SessionApiError(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None, path=None):  # noqa: E501
        """SessionApiError - a model defined in OpenAPI

        :param error: The error of this SessionApiError.  # noqa: E501
        :type error: str
        :param path: The path of this SessionApiError.  # noqa: E501
        :type path: str
        """
        self.openapi_types = {
            'error': str,
            'path': str
        }

        self.attribute_map = {
            'error': 'error',
            'path': 'path'
        }

        self._error = error
        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'SessionApiError':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SessionApiError of this SessionApiError.  # noqa: E501
        :rtype: SessionApiError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this SessionApiError.

        A message describing the error  # noqa: E501

        :return: The error of this SessionApiError.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this SessionApiError.

        A message describing the error  # noqa: E501

        :param error: The error of this SessionApiError.
        :type error: str
        """

        self._error = error

    @property
    def path(self):
        """Gets the path of this SessionApiError.

        The request path  # noqa: E501

        :return: The path of this SessionApiError.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this SessionApiError.

        The request path  # noqa: E501

        :param path: The path of this SessionApiError.
        :type path: str
        """

        self._path = path
