/* 
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.com.github.asyncmc.mojang.api.csharp.api;
using Org.OpenAPITools.com.github.asyncmc.mojang.api.csharp.model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing OrderStatistic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderStatisticTests
    {
        // TODO uncomment below to declare an instance variable for OrderStatistic
        //private OrderStatistic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderStatistic
            //instance = new OrderStatistic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderStatistic
        /// </summary>
        [Test]
        public void OrderStatisticInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderStatistic
            //Assert.IsInstanceOfType<OrderStatistic> (instance, "variable 'instance' is a OrderStatistic");
        }



    }

}
