<?php

/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Mojang Authentication API
 * @version 2020-06-05
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * post authenticate
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->post('/authenticate', 'DefaultApi@authenticate');
/**
 * post invalidate
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->post('/invalidate', 'DefaultApi@invalidate');
/**
 * post refresh
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->post('/refresh', 'DefaultApi@refresh');
/**
 * post siginout
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->post('/signout', 'DefaultApi@siginout');
/**
 * post validate
 * Summary: 
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->post('/validate', 'DefaultApi@validate');

