#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Mojang Authentication API
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* OpenAPI spec version: 2020-06-05
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIGameProfile
@end

@interface OAIGameProfile : OAIObject


@property(nonatomic) NSString* agent;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSURL* userId;
/* Unix timestamp in milliseconds [optional]
 */
@property(nonatomic) NSNumber* createdAt;

@property(nonatomic) NSNumber* legacyProfile;

@property(nonatomic) NSNumber* suspended;

@property(nonatomic) NSNumber* paid;

@property(nonatomic) NSNumber* migrated;

@property(nonatomic) NSNumber* legacy;

@end
