=begin
#Mojang API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

OpenAPI spec version: 2020-06-05

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SkinOperationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SkinOperationsApi' do
  before do
    # run before each test
    @instance = OpenapiClient::SkinOperationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SkinOperationsApi' do
    it 'should create an instance of SkinOperationsApi' do
      expect(@instance).to be_instance_of(OpenapiClient::SkinOperationsApi)
    end
  end

  # unit tests for change_player_skin
  # Changes the player skin by URL
  # This will set the skin for the selected profile, but Mojang&#39;s servers will fetch the skin from a URL. This will also work for legacy accounts.
  # @param stripped_uuid The player UUID without hyphens
  # @param url The URL which Mojang servers will download and apply the skin
  # @param [Hash] opts the optional parameters
  # @option opts [SkinModel] :model 
  # @return [nil]
  describe 'change_player_skin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reset_player_skin
  # Resets the player skin to default
  # @param stripped_uuid The player UUID without hyphens
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'reset_player_skin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for upload_player_skin
  # Changes the player skin by upload
  # This uploads a skin to Mojang&#39;s servers. It also sets the users skin. This works on legacy counts as well.
  # @param stripped_uuid The player UUID without hyphens
  # @param file The skin image in PNG format
  # @param [Hash] opts the optional parameters
  # @option opts [SkinModel] :model 
  # @return [nil]
  describe 'upload_player_skin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
