/**
 * Mojang Session API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PlayerTextureURL'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PlayerTextureURL'));
  } else {
    // Browser globals (root is window)
    if (!root.MojangSessionApi) {
      root.MojangSessionApi = {};
    }
    root.MojangSessionApi.PlayerSkinURL = factory(root.MojangSessionApi.ApiClient, root.MojangSessionApi.PlayerTextureURL);
  }
}(this, function(ApiClient, PlayerTextureURL) {
  'use strict';



  /**
   * The PlayerSkinURL model module.
   * @module model/PlayerSkinURL
   * @version 2020-06-05
   */

  /**
   * Constructs a new <code>PlayerSkinURL</code>.
   * Wraps the URL to the texture and configures the player&#39;s model
   * @alias module:model/PlayerSkinURL
   * @class
   * @extends module:model/PlayerTextureURL
   * @implements module:model/PlayerTextureURL
   * @param url {} The URL to the texture, must be in Mojang's domains.
   */
  var exports = function(url) {
    var _this = this;

    PlayerTextureURL.call(_this, url);
  };

  /**
   * Constructs a <code>PlayerSkinURL</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlayerSkinURL} obj Optional instance to populate.
   * @return {module:model/PlayerSkinURL} The populated <code>PlayerSkinURL</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      PlayerTextureURL.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(PlayerTextureURL.prototype);
  exports.prototype.constructor = exports;


  // Implement PlayerTextureURL interface:
  /**
   * The URL to the texture, must be in Mojang's domains.
   * @member {String} url
   */
exports.prototype['url'] = undefined;



  return exports;
}));


