/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Identifies the software doing the request
 */
export interface Agent {
    /**
     * The name of the game
     */
    "name"?: Agent.NameEnum;
    /**
     * The agent version, usually 1.
     */
    "version"?: number;
}

export namespace Agent {
    export enum NameEnum {
        Minecraft = <any> 'Minecraft',
        Scrolls = <any> 'Scrolls'
    }
}
