<?php
/**
 * OrderStatistic
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.github.asyncmc.mojang.api.php.server
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace com.github.asyncmc.mojang.api.php.server\com.github.asyncmc.mojang.api.php.model;
use \com.github.asyncmc.mojang.api.php.server\ObjectSerializer;

/**
 * OrderStatistic Class Doc Comment
 *
 * @category Class
 * @description Valid options to query the order statistics
 * @package  com.github.asyncmc.mojang.api.php.server
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderStatistic
{
    /**
     * Possible values of this enum
     */
    const ITEM_SOLD_MINECRAFT = 'item_sold_minecraft';
    const PREPAID_CARD_REDEEMED_MINECRAFT = 'prepaid_card_redeemed_minecraft';
    const ITEM_SOLD_COBALT = 'item_sold_cobalt';
    const ITEM_SOLD_SCROLLS = 'item_sold_scrolls';
    const PREPAID_CARD_REDEEMED_COBALT = 'prepaid_card_redeemed_cobalt';
    const ITEM_SOLD_DUNGEONS = 'item_sold_dungeons';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ITEM_SOLD_MINECRAFT,
            self::PREPAID_CARD_REDEEMED_MINECRAFT,
            self::ITEM_SOLD_COBALT,
            self::ITEM_SOLD_SCROLLS,
            self::PREPAID_CARD_REDEEMED_COBALT,
            self::ITEM_SOLD_DUNGEONS,
        ];
    }
}


