/**
 * Mojang Authentication API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 3.3.4.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AuthenticationRequest.h
 *
 * Request body needed to authenticate the player using the username/e-mail and password. Use with care. This is a risky operation.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AuthenticationRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AuthenticationRequest_H_


#include "UsernamePassword.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
/// Request body needed to authenticate the player using the username/e-mail and password. Use with care. This is a risky operation.
/// </summary>
class  AuthenticationRequest
    : public UsernamePassword
{
public:
    AuthenticationRequest();
    virtual ~AuthenticationRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// AuthenticationRequest members


protected:
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AuthenticationRequest_H_ */
