/**
 * Mojang API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2020-06-05
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 3.3.4.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * NameChange.h
 *
 * A registered name change.
 */

#ifndef NameChange_H_
#define NameChange_H_



#include <string>
#include <memory>

namespace com {
namespace github {
namespace asyncmc {
namespace mojang {
namespace api {
namespace cpp {
namespace restbed {
namespace server {
namespace model {

/// <summary>
/// A registered name change.
/// </summary>
class  NameChange
{
public:
    NameChange();
    virtual ~NameChange();
    
    std::string toJsonString();
    void fromJsonString(std::string const& jsonString);

    /////////////////////////////////////////////
    /// NameChange members
    
    /// <summary>
    /// The new player name
    /// </summary>
    std::string getName() const;
    void setName(std::string value);
    /// <summary>
    /// Time which the name was changed in UNIX Timestamp without milliseconds. Usually absent for the first entry.
    /// </summary>
    int64_t getChangedToAt() const;
    void setChangedToAt(int64_t value);

protected:
    std::string m_Name;
    int64_t m_ChangedToAt;
};

}
}
}
}
}
}
}
}
}

#endif /* NameChange_H_ */
