<?php
/**
 * CurrentPlayerIDsTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPIServer\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Mojang API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * OpenAPI spec version: 2020-06-05
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Model\CurrentPlayerIDs;

/**
 * CurrentPlayerIDsTest Class Doc Comment
 *
 * @category Class
 * @description The current player, demo and legacy status of a player identified by the id
 * @package  OpenAPIServer\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 * @coversDefaultClass \OpenAPIServer\Model\CurrentPlayerIDs
 */
class CurrentPlayerIDsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CurrentPlayerIDs"
     */
    public function testCurrentPlayerIDs()
    {
        $testCurrentPlayerIDs = new CurrentPlayerIDs();
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "legacy"
     */
    public function testPropertyLegacy()
    {
    }

    /**
     * Test attribute "demo"
     */
    public function testPropertyDemo()
    {
    }
}
