dependencies:
  factories:
    Articus\DataTransfer\Service: Articus\DataTransfer\ServiceFactory

data_transfer:
  metadata_cache:
    adapter:
      name: blackhole
  strategies:
    invokables:
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\Date: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\Date
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\DateTime: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\DateTime
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameter: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameter
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameterArray: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameterArray
#    factories:
    aliases:
      Date: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\Date
      DateTime: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\DateTime
      QueryParameter: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameter
      QueryParameterArray: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Strategy\QueryParameterArray
  validators:
    invokables:
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\Type: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\Type
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterType: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterType
      com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterArrayType: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterArrayType
    factories:
      Articus\DataTransfer\Validator\Dictionary: Articus\DataTransfer\Validator\Factory
      Articus\DataTransfer\Validator\Collection: Articus\DataTransfer\Validator\Factory
    aliases:
      Dictionary: Articus\DataTransfer\Validator\Dictionary
      Collection: Articus\DataTransfer\Validator\Collection
      Type: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\Type
      QueryParameterType: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterType
      QueryParameterArrayType: com.github.asyncmc.mojang.authentication.php.ze.ph.server\Validator\QueryParameterArrayType
