dependencies:
  factories:
    Zend\Expressive\Router\RouterInterface: Articus\PathHandler\Router\Factory\FastRouteAnnotation

Articus\PathHandler\Middleware:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    abstract_factories:
      - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Articus\PathHandler\Router\FastRouteAnnotation:
  metadata_cache:
    adapter:
      name: blackhole
  handlers:
    - App\Handler\Authenticate
    - App\Handler\Invalidate
    - App\Handler\Refresh
    - App\Handler\Signout
    - App\Handler\Validate

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\Authenticate: []
  App\Handler\Invalidate: []
  App\Handler\Refresh: []
  App\Handler\Signout: []
  App\Handler\Validate: []
