//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire


open class DefaultAPI: APIBase {
    /**
     Checks the Mojang service statuses
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func checkStatuses(completion: @escaping ((_ data: [[String:ApiStatus]]?, _ error: ErrorResponse?) -> Void)) {
        checkStatusesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Checks the Mojang service statuses
     - GET /check
     - returns: RequestBuilder<[[String:ApiStatus]]> 
     */
    open class func checkStatusesWithRequestBuilder() -> RequestBuilder<[[String:ApiStatus]]> {
        let path = "/check"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<[[String:ApiStatus]]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
